upstream vllm_backends {
    server 127.0.0.1:8001;
    server 127.0.0.1:8003;
    server 127.0.0.1:8004;
    server 127.0.0.1:8005;
    server 127.0.0.1:8006;
}

server {
    listen 8888;
    client_max_body_size 10m;
    proxy_read_timeout 300s;
    proxy_connect_timeout 10s;

    location / {
        proxy_pass http://vllm_backends;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
