#!/bin/bash
# scripts/launch_cell.sh — one-click launch of one 2x2 cell on a single pod.
#
# Architecture: iterate.py orchestrates a fleet of 8 vLLM HTTP servers
# (one per GPU, TP=1 each) plus a Parliament HTTP server, both as
# subprocesses.  vLLMs stay alive across all training iters; LoRA
# adapters hot-swap via /v1/load_lora_adapter and KV cache is freed
# during training via /sleep + /wake_up.
#
# Usage:
#   bash scripts/launch_cell.sh <CELL> <PROJECT_DIR> <PYTHON> <MODEL_PATH> [iterate.py extra args...]
#
# CELL ∈ {A,B,C,D}:
#   A = Parliament       (PRL_CONTEXT=Parliament, judge votes visible)
#   B = BlindParliament  (PRL_CONTEXT=Parliament, judge votes hidden)
#   C = Solo             (PRL_CONTEXT=Solo,       judge votes visible)
#   D = BlindSolo        (PRL_CONTEXT=Solo,       judge votes hidden)
#
# What it does:
#   1. Pre-flight: kill leftover iterate / parliament / vllm processes
#      and tmux sessions, including any vllm-gpuN tmux sessions from
#      a previous run (iterate.py's run.ensure_vllm() launches one
#      tmux per GPU as 'vllm-gpu{N}').
#   2. Launch iterate.py in tmux 'parliament-iterate' (detached).
#   3. Launch a 'keepalive-watcher' tmux that takes over the pod
#      with gpu_keepalive.py once the training run finishes.
#
# All env-vars (PRL_CONTEXT etc.) are baked into the cmdline so they
# survive the tmux session boundary.

set -euo pipefail

if [[ $# -lt 4 ]]; then
  echo "Usage: $0 <A|B|C|D> <PROJECT_DIR> <PYTHON> <MODEL_PATH> [iterate.py extra args...]"
  echo "Example:"
  echo "  $0 A /path/to/parliament_rl /path/to/python_env/bin/python /path/to/Qwen3.5-9B \\"
  echo "    --name smokeA --pool datasets/sciencepedia_train_part1.json \\"
  echo "    --total-questions 200 --sampling-batch-size 200 --total-epochs 8 --seed 42 \\"
  echo "    --gpus 0,1,2,3,4,5,6,7 --sessions-per-gpu 4 \\"
  echo "    --max-concurrent-sessions 16 --actors 3 --judges 3 --max-turns 30"
  exit 1
fi

CELL=$1
PROJECT_DIR=$2
PYTHON=$3
MODEL_PATH=$4
shift 4
ITERATE_EXTRA=("$@")

case "$CELL" in
  A) export PRL_CONTEXT=Parliament; export PRL_JUDGE_VOTES_VISIBLE=1 ;;
  B) export PRL_CONTEXT=Parliament; export PRL_JUDGE_VOTES_VISIBLE=0 ;;
  C) export PRL_CONTEXT=Solo;       export PRL_JUDGE_VOTES_VISIBLE=1 ;;
  D) export PRL_CONTEXT=Solo;       export PRL_JUDGE_VOTES_VISIBLE=0 ;;
  *) echo "ERROR: CELL must be one of A B C D (got '$CELL')"; exit 1 ;;
esac

ACCELERATE="${PYTHON%/python}/accelerate"
[[ -x "$ACCELERATE" ]] || { echo "ERROR: accelerate not found at $ACCELERATE"; exit 1; }
[[ -x "$PYTHON" ]]     || { echo "ERROR: python not found at $PYTHON"; exit 1; }
[[ -d "$MODEL_PATH" ]] || { echo "ERROR: model dir not found at $MODEL_PATH"; exit 1; }
[[ -d "$PROJECT_DIR" ]] || { echo "ERROR: project dir not found at $PROJECT_DIR"; exit 1; }

echo "============================================================"
echo "CELL $CELL  HOST $(hostname)  TIME $(date '+%Y-%m-%d %H:%M:%S')"
echo "  PROJECT_DIR  : $PROJECT_DIR"
echo "  PYTHON       : $PYTHON"
echo "  MODEL_PATH   : $MODEL_PATH"
echo "  PRL_CONTEXT             = $PRL_CONTEXT"
echo "  PRL_JUDGE_VOTES_VISIBLE = $PRL_JUDGE_VOTES_VISIBLE"
echo "  iterate extra: ${ITERATE_EXTRA[*]}"
echo "============================================================"

echo "[1/3] Cleanup leftover processes..."
pkill -9 -f 'iterate.py'         2>/dev/null || true
pkill -9 -f 'parliament.server'  2>/dev/null || true
pkill -9 -f 'vllm.entrypoints'   2>/dev/null || true
pkill -9 -f 'VLLM::EngineCore'   2>/dev/null || true
pkill -9 -f 'gpu_keepalive'      2>/dev/null || true
pkill -9 -f 'keepalive_watcher'  2>/dev/null || true
tmux kill-session -t parliament-iterate 2>/dev/null || true
tmux kill-session -t keepalive-watcher  2>/dev/null || true
# Per-GPU vLLM tmux sessions (one per card, named vllm-gpu{N})
for i in 0 1 2 3 4 5 6 7; do
  tmux kill-session -t "vllm-gpu${i}" 2>/dev/null || true
done
sleep 3
echo "  GPU memory after cleanup:"
nvidia-smi --query-gpu=index,memory.used --format=csv,noheader,nounits | sed 's/^/    /'

echo "[2/3] Launch iterate.py in tmux 'parliament-iterate'..."
export PRL_PYTHON="$PYTHON"
export PRL_ACCELERATE="$ACCELERATE"
export PRL_MODEL_PATH="$MODEL_PATH"
export TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=7200
export PYTORCH_ALLOC_CONF=expandable_segments:True
cd "$PROJECT_DIR"
"$PYTHON" scripts/iterate.py "${ITERATE_EXTRA[@]}"

echo "[3/3] Launch keepalive-watcher in tmux..."
WATCHER=/tmp/keepalive_watcher_${CELL}.sh
cat > "$WATCHER" << EOF
#!/bin/bash
# auto-generated by launch_cell.sh on $(date)
LOG=/tmp/keepalive_watcher_${CELL}.log
echo "[\$(date)] watcher start (cell ${CELL})" > "\$LOG"
while true; do
  if ! pgrep -f 'iterate.py'        > /dev/null \\
   && ! pgrep -f 'parliament.server' > /dev/null; then
    echo "[\$(date)] iterate done, exec gpu_keepalive on all 8 GPUs" >> "\$LOG"
    cd "$PROJECT_DIR"
    exec "$PYTHON" scripts/gpu_keepalive.py --gpus 0,1,2,3,4,5,6,7
  fi
  sleep 60
done
EOF
chmod +x "$WATCHER"
tmux new-session -d -s keepalive-watcher \
  "bash $WATCHER 2>&1 | tee /tmp/keepalive_watcher_${CELL}.tmux.log"

echo
echo "Done. tmux sessions:"
tmux ls
echo
echo "Tail commands:"
echo "  tail -f \$(ls -t $PROJECT_DIR/data/*_*/iterate.log | head -1)"
echo "  tmux attach -t parliament-iterate"
echo "  tmux attach -t keepalive-watcher"
